name: Generate screenshots

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-screenshots-android:
    name: Generate screenshots Android - Main
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT_GRADLE_WRAPPER }}

      - name: Test push
        run: echo "Hello" > hello.txt

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Test push
          push_options: --force

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: adopt
#          java-version: 17
#
#      - name: Generate screenshots
#        run: ./gradlew updateScreenshotTest
#
#      - name: Commit & Push changes
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: New @Preview screenshots!
#          push_options: --force